# Generated by Django 6.0.4 on 2026-04-11 11:57

import core.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_categories_defects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Код в адресе'),
        ),
        migrations.AlterField(
            model_name='defecttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='defecttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='defecttype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='defect_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.defecttype', verbose_name='Тип дефекта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_discounted',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_original',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'В продаже'), ('reserved', 'Забронирован'), ('sold', 'Продан'), ('archived', 'В архиве')], db_index=True, default='available', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.store', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(default=core.models._default_reservation_code, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Код должен состоять из 4 цифр.')], verbose_name='Код брони'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='visit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'manager'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='store',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Часы работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Покупатель'), ('manager', 'Управляющий магазина')], default='buyer', max_length=20, verbose_name='Роль'),
        ),
    ]
