# Generated by Django 6.0.4 on 2026-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_verbose_names_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон для связи'),
        ),
    ]
