# Generated by Django 6.0.4 on 2026-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservation_contact_three_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Город'),
        ),
    ]
